package utn.tacs.grupo5.telegrambot;

public enum UserState {
    AWAITING_SESSION,
    LOGIN_IN,
    REGISTERING,
    CHOOSING_OPTIONS,
    CHOOSING_GAME,
    CHOOSING_CARD,
    CHOOSING_CONDITION,
    CHOOSING_VALUE,
    CHOOSING_PHOTO_OPTION,
    CHOOSING_PHOTO,
    CHOOSING_DESCRIPTION,
    CHOOSING_VALUE_TYPE,
    CREATING_POST,
    SELECTING_CARD,
    SELECTING_INDEX,
    SELECTING_OFFERED_CARD,
    SELECTING_WANTED_CARDS,
    CHOOSING_POST_FILTERS, SELECTING_POST, SHOWING_POSTS_FILTERS_RESULTS, CREATING_OFFER, MAKING_OFFER
}
