services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'TELEGRAM_BOT_TOKEN=7419881340:AAHoboaIik9jv_LsSUo79Mlrs3VcEmttYHU'
      - 'TELEGRAM_BOT_NAME=CardsTradingbot'
      - 'TELEGRAM_CREATOR_ID=6149031583'
    ports:
      - '27017'
