version: '3.8'

services:
  # mongodb:
  #   image: 'mongo:latest'
  #   environment:
  #     - 'MONGO_INITDB_DATABASE=mydatabase'
  #     - 'MONGO_INITDB_ROOT_PASSWORD=secret'
  #     - 'MONGO_INITDB_ROOT_USERNAME=root'
  #   ports:
  #     - '27017'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tacs-2025-1c-grupo5-backend:latest
    ports:
      - '8080:8080'
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    image: tacs-2025-1c-grupo5-frontend:latest
    ports:
      - '3000:3000'
    networks:
      - default