version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tacs-2025-1c-grupo5-backend:latest
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - YUGIOH_API_URL=${YUGIOH_API_URL}
      - MAGIC_API_URL=${MAGIC_API_URL}
      - POKEMON_API_URL=${POKEMON_API_URL}
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - mongo

  backend-telegram-bot:
    build:
      context: ./backend-telegram-bot
      dockerfile: Dockerfile
    image: tacs-2025-1c-grupo5-backend-telegram-bot:latest
    environment:
      - BACKEND_URL=${BACKEND_URL_LOCAL}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CREATOR_ID=${TELEGRAM_CREATOR_ID}
    networks:
      - default
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${BACKEND_URL}/api
    image: tacs-2025-1c-grupo5-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - backend

volumes:
  mongo-data:
