spring:
  application:
    name: tacs-2025-1c-grupo5
  profiles:
    active: dev

server:
  servlet:
    contextPath: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui
  packages-to-scan: utn.tacs.grupo5.controller
  pathsToMatch: /**
