package utn.tacs.grupo5.bot;

public enum UserState {
    AWAITING_SESSION,
    LOGIN_IN,
    REGISTERING,
    CHOOSING_OPTIONS,
    CHOOSING_GAME,
    CHOOSING_CARD,
    CHOOSING_CONDITION,
    CHOOSING_VALUE,
    CHOOSING_PHOTO_PUBLICATION,
    CHOOSING_DESCRIPTION,
    CHOOSING_VALUE_TYPE, MAKING_OFFER
}
