spring:
  application:
    name: tacs-2025-1c-grupo5
  profiles:
    active: dev

server:
  servlet:
    contextPath: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
  packages-to-scan: utn.tacs.grupo5.controller
  pathsToMatch: /**

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    name: ${TELEGRAM_BOT_NAME}
    cid: ${TELEGRAM_CREATOR_ID}