spring:
  application:
    name: tacs-2025-1c-grupo5
  data:
    mongodb:
      uri: mongodb://localhost:27017/tacs-2025-1c-grupo5
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  codec:
    max-in-memory-size: 10MB

external:
  api:
    magic:
      url: http://localhost:8081
    pokemon:
      url: http://localhost:8082
    yugioh:
      url: http://localhost:8083

server:
  servlet:
    contextPath: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
  packages-to-scan: utn.tacs.grupo5.controller
  pathsToMatch: /**
