spring:
  application:
    name: tacs-2025-1c-grupo5
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  codec:
    max-in-memory-size: 10MB

server:
  servlet:
    contextPath: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
  packages-to-scan: utn.tacs.grupo5.controller
  pathsToMatch: /**
