name: Java CI with Maven

on:
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Build and verify with Maven
        run: mvn clean verify

      - name: Generate JaCoCo coverage report
        run: mvn jacoco:report
        continue-on-error: true

      - name: Run SpotBugs
        run: mvn spotbugs:check

      - name: Build Docker image
        run: docker build -t tacs-app:ci-test .

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: tacs-app:ci-test
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
